import { describe, it, expect, beforeEach } from 'vitest';
import { db } from '../database';
import {
  createTrip,
  updateTrip,
  deleteTrip,
  duplicateTrip,
  addPackingItem,
  addPackingItems,
  updatePackingItem,
  deletePackingItem,
  togglePacked,
  deleteAutoGeneratedItems,
  renameCategory,
  learnItem,
  removeLearnedItems,
  getLearnedNewItems,
  getTripDays,
  getLongestStretch,
} from '../hooks';
import type { Trip } from '../models';

function makeTripData(): Omit<Trip, 'id'> {
  return {
    destination: 'Paris',
    startDate: '2026-04-01',
    endDate: '2026-04-08',
    hasLaundry: false,
    laundryDates: [],
    rewearDays: 1,
    activities: ['Sightseeing'],
    isInternational: true,
    transportation: ['Flight'],
    feedbackRating: 0,
    feedbackUnpacked: [],
    feedbackWishlist: '',
    hasSubmittedFeedback: false,
  };
}

beforeEach(async () => {
  await db.trips.clear();
  await db.packingItems.clear();
  await db.learnedItems.clear();
});

// ── Trip CRUD ──

describe('Trip operations', () => {
  it('createTrip returns trip with ID', async () => {
    const trip = await createTrip(makeTripData());
    expect(trip.id).toBeDefined();
    expect(trip.destination).toBe('Paris');
    const stored = await db.trips.get(trip.id);
    expect(stored?.destination).toBe('Paris');
  });

  it('createTrip with items creates both atomically', async () => {
    const items = [
      { tripId: '', name: 'Tops', category: 'Clothing', quantity: 3, isPacked: false, isMustPack: false, isAutoGenerated: true },
      { tripId: '', name: 'Passport', category: 'Essentials', quantity: 1, isPacked: false, isMustPack: true, isAutoGenerated: true },
    ];
    const trip = await createTrip(makeTripData(), items);
    const storedItems = await db.packingItems.where('tripId').equals(trip.id).toArray();
    expect(storedItems).toHaveLength(2);
    expect(storedItems.every(i => i.tripId === trip.id)).toBe(true);
    expect(storedItems.every(i => i.id)).toBe(true);
  });

  it('createTrip without items creates trip only', async () => {
    const trip = await createTrip(makeTripData());
    const items = await db.packingItems.where('tripId').equals(trip.id).toArray();
    expect(items).toHaveLength(0);
  });

  it('updateTrip changes the specified fields', async () => {
    const trip = await createTrip(makeTripData());
    await updateTrip(trip.id, { destination: 'London' });
    const updated = await db.trips.get(trip.id);
    expect(updated?.destination).toBe('London');
    expect(updated?.startDate).toBe('2026-04-01'); // unchanged
  });

  it('deleteTrip cascades to packing items', async () => {
    const items = [
      { tripId: '', name: 'Tops', category: 'Clothing', quantity: 3, isPacked: false, isMustPack: false, isAutoGenerated: true },
    ];
    const trip = await createTrip(makeTripData(), items);
    await deleteTrip(trip.id);
    expect(await db.trips.get(trip.id)).toBeUndefined();
    const remaining = await db.packingItems.where('tripId').equals(trip.id).toArray();
    expect(remaining).toHaveLength(0);
  });

  it('duplicateTrip copies items with new IDs and isPacked=false', async () => {
    const items = [
      { tripId: '', name: 'Tops', category: 'Clothing', quantity: 3, isPacked: true, isMustPack: false, isAutoGenerated: true },
    ];
    const original = await createTrip(makeTripData(), items);
    const dupe = await duplicateTrip({ ...makeTripData(), id: original.id } as Trip);
    expect(dupe.id).not.toBe(original.id);

    const dupeItems = await db.packingItems.where('tripId').equals(dupe.id).toArray();
    expect(dupeItems).toHaveLength(1);
    expect(dupeItems[0].isPacked).toBe(false);
    expect(dupeItems[0].tripId).toBe(dupe.id);
    expect(dupeItems[0].id).not.toBe((await db.packingItems.where('tripId').equals(original.id).first())?.id);
  });

  it('duplicateTrip resets feedback fields', async () => {
    const data = makeTripData();
    const original = await createTrip(data);
    await updateTrip(original.id, { feedbackRating: 4, hasSubmittedFeedback: true });
    const updated = await db.trips.get(original.id);
    const dupe = await duplicateTrip(updated!);
    expect(dupe.feedbackRating).toBe(0);
    expect(dupe.hasSubmittedFeedback).toBe(false);
    expect(dupe.feedbackWishlist).toBe('');
  });
});

// ── Packing Item CRUD ──

describe('PackingItem operations', () => {
  it('addPackingItem returns item with generated ID', async () => {
    const trip = await createTrip(makeTripData());
    const item = await addPackingItem({
      tripId: trip.id, name: 'Sunscreen', category: 'Beach',
      quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: false,
    });
    expect(item.id).toBeDefined();
    expect(await db.packingItems.get(item.id)).toBeDefined();
  });

  it('addPackingItems adds multiple items', async () => {
    const trip = await createTrip(makeTripData());
    const items = await addPackingItems([
      { tripId: trip.id, name: 'A', category: 'C', quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: true },
      { tripId: trip.id, name: 'B', category: 'C', quantity: 2, isPacked: false, isMustPack: false, isAutoGenerated: true },
    ]);
    expect(items).toHaveLength(2);
    const stored = await db.packingItems.where('tripId').equals(trip.id).toArray();
    expect(stored).toHaveLength(2);
  });

  it('updatePackingItem changes fields', async () => {
    const trip = await createTrip(makeTripData());
    const item = await addPackingItem({
      tripId: trip.id, name: 'Old', category: 'Cat',
      quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: false,
    });
    await updatePackingItem(item.id, { name: 'New', quantity: 5 });
    const updated = await db.packingItems.get(item.id);
    expect(updated?.name).toBe('New');
    expect(updated?.quantity).toBe(5);
  });

  it('deletePackingItem removes the item', async () => {
    const trip = await createTrip(makeTripData());
    const item = await addPackingItem({
      tripId: trip.id, name: 'X', category: 'C',
      quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: false,
    });
    await deletePackingItem(item.id);
    expect(await db.packingItems.get(item.id)).toBeUndefined();
  });

  it('togglePacked sets isPacked to true', async () => {
    const trip = await createTrip(makeTripData());
    const item = await addPackingItem({
      tripId: trip.id, name: 'X', category: 'C',
      quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: false,
    });
    await togglePacked(item.id, true);
    expect((await db.packingItems.get(item.id))?.isPacked).toBe(true);
  });

  it('togglePacked sets isPacked to false', async () => {
    const trip = await createTrip(makeTripData());
    const item = await addPackingItem({
      tripId: trip.id, name: 'X', category: 'C',
      quantity: 1, isPacked: true, isMustPack: false, isAutoGenerated: false,
    });
    await togglePacked(item.id, false);
    expect((await db.packingItems.get(item.id))?.isPacked).toBe(false);
  });

  it('deleteAutoGeneratedItems only removes auto-generated items', async () => {
    const trip = await createTrip(makeTripData());
    await addPackingItems([
      { tripId: trip.id, name: 'Auto', category: 'C', quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: true },
      { tripId: trip.id, name: 'Manual', category: 'C', quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: false },
    ]);
    await deleteAutoGeneratedItems(trip.id);
    const remaining = await db.packingItems.where('tripId').equals(trip.id).toArray();
    expect(remaining).toHaveLength(1);
    expect(remaining[0].name).toBe('Manual');
  });

  it('renameCategory updates all items in old category', async () => {
    const trip = await createTrip(makeTripData());
    await addPackingItems([
      { tripId: trip.id, name: 'A', category: 'OldCat', quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: true },
      { tripId: trip.id, name: 'B', category: 'OldCat', quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: true },
      { tripId: trip.id, name: 'C', category: 'Other', quantity: 1, isPacked: false, isMustPack: false, isAutoGenerated: true },
    ]);
    await renameCategory(trip.id, 'OldCat', 'NewCat');
    const items = await db.packingItems.where('tripId').equals(trip.id).toArray();
    const renamed = items.filter(i => i.category === 'NewCat');
    const unchanged = items.filter(i => i.category === 'Other');
    expect(renamed).toHaveLength(2);
    expect(unchanged).toHaveLength(1);
  });
});

// ── Learned Items ──

describe('LearnedItem operations', () => {
  it('learnItem adds with lowercase name', async () => {
    await learnItem({ name: 'Sunscreen', category: 'Beach', quantity: 1, isMustPack: false });
    const stored = await db.learnedItems.get('sunscreen');
    expect(stored).toBeDefined();
    expect(stored?.name).toBe('sunscreen');
  });

  it('learnItem ignores duplicate names', async () => {
    await learnItem({ name: 'Sunscreen', category: 'Beach', quantity: 1, isMustPack: false });
    await learnItem({ name: 'Sunscreen', category: 'Health', quantity: 2, isMustPack: true });
    const all = await db.learnedItems.toArray();
    expect(all).toHaveLength(1);
    expect(all[0].category).toBe('Beach'); // first one wins
  });

  it('learnItem is case insensitive for dedup', async () => {
    await learnItem({ name: 'Sunscreen', category: 'Beach', quantity: 1, isMustPack: false });
    await learnItem({ name: 'sunscreen', category: 'Health', quantity: 2, isMustPack: true });
    const all = await db.learnedItems.toArray();
    expect(all).toHaveLength(1);
  });

  it('removeLearnedItems removes by name', async () => {
    await learnItem({ name: 'A', category: 'C', quantity: 1, isMustPack: false });
    await learnItem({ name: 'B', category: 'C', quantity: 1, isMustPack: false });
    await removeLearnedItems(['A']);
    const all = await db.learnedItems.toArray();
    expect(all).toHaveLength(1);
    expect(all[0].name).toBe('b');
  });

  it('getLearnedNewItems filters out existing names', async () => {
    await learnItem({ name: 'Sunscreen', category: 'B', quantity: 1, isMustPack: false });
    await learnItem({ name: 'Towel', category: 'B', quantity: 1, isMustPack: false });
    const newItems = await getLearnedNewItems(['Sunscreen']);
    expect(newItems).toHaveLength(1);
    expect(newItems[0].name).toBe('towel');
  });
});

// ── Utility functions ──

describe('Utility functions', () => {
  it('getTripDays returns inclusive day count', () => {
    expect(getTripDays('2026-04-01', '2026-04-08')).toBe(7);
  });

  it('getTripDays returns minimum 1', () => {
    expect(getTripDays('2026-04-01', '2026-04-01')).toBe(1);
  });

  it('getLongestStretch returns full trip days without laundry', () => {
    expect(getLongestStretch('2026-04-01', '2026-04-08', false, [])).toBe(7);
  });

  it('getLongestStretch returns max gap with laundry', () => {
    // 10 day trip, laundry on day 5 → max(5, 5) = 5
    expect(getLongestStretch('2026-04-01', '2026-04-11', true, ['2026-04-06'])).toBe(5);
  });

  it('getLongestStretch handles multiple laundry days', () => {
    // 10 day trip, laundry on day 3 and day 7 → gaps: 3, 4, 3 → max = 4
    expect(getLongestStretch('2026-04-01', '2026-04-11', true, ['2026-04-04', '2026-04-08'])).toBe(4);
  });
});
