import { useLiveQuery } from 'dexie-react-hooks';
import { db } from './database';
import type { Trip, PackingItem, LearnedItem } from './models';
import { v4 as uuidv4 } from 'uuid';

// ── Typed DB Error ──

export class DbError extends Error {
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = 'DbError';
  }
}

// ── Queries ──

export function useTrips() {
  return useLiveQuery(() => db.trips.orderBy('startDate').reverse().toArray()) ?? [];
}

export function useTrip(id: string | undefined) {
  return useLiveQuery(() => (id ? db.trips.get(id) : undefined), [id]);
}

export function usePackingItems(tripId: string | undefined) {
  return useLiveQuery(
    () => (tripId ? db.packingItems.where('tripId').equals(tripId).toArray() : []),
    [tripId]
  ) ?? [];
}

export function useLearnedItems() {
  return useLiveQuery(() => db.learnedItems.toArray()) ?? [];
}

// ── Trip CRUD ──

export async function createTrip(
  data: Omit<Trip, 'id'>,
  items?: Omit<PackingItem, 'id'>[]
): Promise<Trip> {
  const trip: Trip = { ...data, id: uuidv4() };
  try {
    await db.transaction('rw', db.trips, db.packingItems, async () => {
      await db.trips.add(trip);
      if (items && items.length > 0) {
        const withIds = items.map(item => ({ ...item, id: uuidv4(), tripId: trip.id }));
        await db.packingItems.bulkAdd(withIds);
      }
    });
  } catch (e) {
    throw new DbError('Failed to create trip', e);
  }
  return trip;
}

export async function updateTrip(id: string, changes: Partial<Trip>) {
  try {
    await db.trips.update(id, changes);
  } catch (e) {
    throw new DbError('Failed to update trip', e);
  }
}

export async function deleteTrip(id: string) {
  try {
    await db.transaction('rw', db.trips, db.packingItems, async () => {
      await db.packingItems.where('tripId').equals(id).delete();
      await db.trips.delete(id);
    });
  } catch (e) {
    throw new DbError('Failed to delete trip', e);
  }
}

export async function duplicateTrip(source: Trip): Promise<Trip> {
  const newTrip: Trip = {
    ...source,
    id: uuidv4(),
    feedbackRating: 0,
    feedbackUnpacked: [],
    feedbackWishlist: '',
    hasSubmittedFeedback: false,
  };
  try {
    await db.transaction('rw', db.trips, db.packingItems, async () => {
      await db.trips.add(newTrip);
      // Copy packing items from source trip
      const sourceItems = await db.packingItems.where('tripId').equals(source.id).toArray();
      if (sourceItems.length > 0) {
        const copies = sourceItems.map(item => ({
          ...item,
          id: uuidv4(),
          tripId: newTrip.id,
          isPacked: false,
        }));
        await db.packingItems.bulkAdd(copies);
      }
    });
  } catch (e) {
    throw new DbError('Failed to duplicate trip', e);
  }
  return newTrip;
}

// ── Packing Item CRUD ──

export async function addPackingItems(items: Omit<PackingItem, 'id'>[]) {
  const withIds = items.map(item => ({ ...item, id: uuidv4() }));
  try {
    await db.packingItems.bulkAdd(withIds);
  } catch (e) {
    throw new DbError('Failed to add packing items', e);
  }
  return withIds;
}

export async function addPackingItem(item: Omit<PackingItem, 'id'>): Promise<PackingItem> {
  const withId: PackingItem = { ...item, id: uuidv4() };
  try {
    await db.packingItems.add(withId);
  } catch (e) {
    throw new DbError('Failed to add packing item', e);
  }
  return withId;
}

export async function updatePackingItem(id: string, changes: Partial<PackingItem>) {
  try {
    await db.packingItems.update(id, changes);
  } catch (e) {
    throw new DbError('Failed to update packing item', e);
  }
}

export async function deletePackingItem(id: string) {
  try {
    await db.packingItems.delete(id);
  } catch (e) {
    throw new DbError('Failed to delete packing item', e);
  }
}

export async function togglePacked(id: string, isPacked: boolean) {
  try {
    await db.packingItems.update(id, { isPacked });
  } catch (e) {
    throw new DbError('Failed to toggle packed state', e);
  }
}

export async function deleteAutoGeneratedItems(tripId: string) {
  try {
    await db.packingItems
      .where('tripId').equals(tripId)
      .filter(item => item.isAutoGenerated)
      .delete();
  } catch (e) {
    throw new DbError('Failed to delete auto-generated items', e);
  }
}

export async function renameCategory(tripId: string, oldName: string, newName: string) {
  try {
    const items = await db.packingItems
      .where('tripId').equals(tripId)
      .filter(item => item.category === oldName)
      .toArray();
    await db.packingItems.bulkPut(items.map(item => ({ ...item, category: newName })));
  } catch (e) {
    throw new DbError('Failed to rename category', e);
  }
}

// ── Learned Items ──

export async function learnItem(item: { name: string; category: string; quantity: number; isMustPack: boolean }) {
  try {
    // Normalize to lowercase for both lookup and storage key
    const normalizedName = item.name.toLowerCase();
    const existing = await db.learnedItems.get(normalizedName);
    if (existing) return;
    await db.learnedItems.add({
      name: normalizedName,
      category: item.category,
      quantity: item.quantity,
      isMustPack: item.isMustPack,
    });
  } catch (e) {
    throw new DbError('Failed to learn item', e);
  }
}

export async function removeLearnedItems(names: string[]) {
  try {
    const lower = names.map(n => n.toLowerCase());
    // Use indexed query instead of full table scan
    await db.learnedItems.where('name').anyOf(lower).delete();
  } catch (e) {
    throw new DbError('Failed to remove learned items', e);
  }
}

export async function getLearnedNewItems(existingNames: string[]): Promise<LearnedItem[]> {
  try {
    const lower = new Set(existingNames.map(n => n.toLowerCase()));
    const all = await db.learnedItems.toArray();
    return all.filter(i => !lower.has(i.name.toLowerCase()));
  } catch (e) {
    throw new DbError('Failed to get learned items', e);
  }
}

// ── Unused Items (localStorage-backed) ──

const UNUSED_KEY = 'readiLi.unusedItems';

export function getUnusedNames(): Set<string> {
  try {
    const arr = JSON.parse(localStorage.getItem(UNUSED_KEY) || '[]') as string[];
    return new Set(arr);
  } catch {
    return new Set();
  }
}

export function markUnused(names: string[]) {
  // Atomic read-modify-write to prevent race conditions
  const raw = localStorage.getItem(UNUSED_KEY) || '[]';
  let current: Set<string>;
  try {
    current = new Set(JSON.parse(raw) as string[]);
  } catch {
    current = new Set();
  }
  names.forEach(n => current.add(n.toLowerCase()));
  localStorage.setItem(UNUSED_KEY, JSON.stringify([...current]));
}

export function clearUnused(names: string[]) {
  const raw = localStorage.getItem(UNUSED_KEY) || '[]';
  let current: Set<string>;
  try {
    current = new Set(JSON.parse(raw) as string[]);
  } catch {
    current = new Set();
  }
  names.forEach(n => current.delete(n.toLowerCase()));
  localStorage.setItem(UNUSED_KEY, JSON.stringify([...current]));
}

// ── Utility ──

export function getTripDays(startDate: string, endDate: string): number {
  const start = new Date(startDate);
  const end = new Date(endDate);
  const diff = Math.round((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
  return Math.max(diff, 1);
}

export function getLongestStretch(
  startDate: string,
  endDate: string,
  hasLaundry: boolean,
  laundryDates: string[]
): number {
  const tripDays = getTripDays(startDate, endDate);
  if (!hasLaundry || laundryDates.length === 0) return tripDays;

  const start = new Date(startDate).getTime();
  const end = new Date(endDate).getTime();
  const sorted = laundryDates.map(d => new Date(d).getTime()).sort((a, b) => a - b);
  const boundaries = [start, ...sorted, end];

  let maxGap = 0;
  for (let i = 1; i < boundaries.length; i++) {
    const gap = Math.round((boundaries[i] - boundaries[i - 1]) / (1000 * 60 * 60 * 24));
    maxGap = Math.max(maxGap, gap);
  }
  return Math.max(maxGap, 1);
}

export function getFormattedDateRange(startDate: string, endDate: string): string {
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric', year: 'numeric' };
  const start = new Date(startDate).toLocaleDateString('en-US', opts);
  const end = new Date(endDate).toLocaleDateString('en-US', opts);
  return `${start} – ${end}`;
}
