import { useLiveQuery } from 'dexie-react-hooks';
import { db } from './database';
import type { Trip, PackingItem, LearnedItem } from './models';
import { v4 as uuidv4 } from 'uuid';

// ── Queries ──

export function useTrips() {
  return useLiveQuery(() => db.trips.orderBy('startDate').reverse().toArray()) ?? [];
}

export function useTrip(id: string | undefined) {
  return useLiveQuery(() => (id ? db.trips.get(id) : undefined), [id]);
}

export function usePackingItems(tripId: string | undefined) {
  return useLiveQuery(
    () => (tripId ? db.packingItems.where('tripId').equals(tripId).toArray() : []),
    [tripId]
  ) ?? [];
}

export function useLearnedItems() {
  return useLiveQuery(() => db.learnedItems.toArray()) ?? [];
}

// ── Trip CRUD ──

export async function createTrip(data: Omit<Trip, 'id'>): Promise<Trip> {
  const trip: Trip = { ...data, id: uuidv4() };
  await db.trips.add(trip);
  return trip;
}

export async function updateTrip(id: string, changes: Partial<Trip>) {
  await db.trips.update(id, changes);
}

export async function deleteTrip(id: string) {
  await db.transaction('rw', db.trips, db.packingItems, async () => {
    await db.packingItems.where('tripId').equals(id).delete();
    await db.trips.delete(id);
  });
}

export async function duplicateTrip(source: Trip): Promise<Trip> {
  const newTrip: Trip = {
    ...source,
    id: uuidv4(),
    feedbackRating: 0,
    feedbackUnpacked: [],
    feedbackWishlist: '',
    hasSubmittedFeedback: false,
  };
  await db.trips.add(newTrip);
  return newTrip;
}

// ── Packing Item CRUD ──

export async function addPackingItems(items: Omit<PackingItem, 'id'>[]) {
  const withIds = items.map(item => ({ ...item, id: uuidv4() }));
  await db.packingItems.bulkAdd(withIds);
  return withIds;
}

export async function addPackingItem(item: Omit<PackingItem, 'id'>): Promise<PackingItem> {
  const withId: PackingItem = { ...item, id: uuidv4() };
  await db.packingItems.add(withId);
  return withId;
}

export async function updatePackingItem(id: string, changes: Partial<PackingItem>) {
  await db.packingItems.update(id, changes);
}

export async function deletePackingItem(id: string) {
  await db.packingItems.delete(id);
}

export async function togglePacked(id: string, isPacked: boolean) {
  await db.packingItems.update(id, { isPacked });
}

export async function deleteAutoGeneratedItems(tripId: string) {
  await db.packingItems
    .where('tripId').equals(tripId)
    .filter(item => item.isAutoGenerated)
    .delete();
}

export async function renameCategory(tripId: string, oldName: string, newName: string) {
  const items = await db.packingItems
    .where('tripId').equals(tripId)
    .filter(item => item.category === oldName)
    .toArray();
  await db.packingItems.bulkPut(items.map(item => ({ ...item, category: newName })));
}

// ── Learned Items ──

export async function learnItem(item: { name: string; category: string; quantity: number; isMustPack: boolean }) {
  const existing = await db.learnedItems.get(item.name.toLowerCase());
  if (existing) return;
  await db.learnedItems.add({
    name: item.name,
    category: item.category,
    quantity: item.quantity,
    isMustPack: item.isMustPack,
  });
}

export async function removeLearnedItems(names: string[]) {
  const lower = names.map(n => n.toLowerCase());
  const all = await db.learnedItems.toArray();
  const toDelete = all.filter(i => lower.includes(i.name.toLowerCase())).map(i => i.name);
  await db.learnedItems.bulkDelete(toDelete);
}

export async function getLearnedNewItems(existingNames: string[]): Promise<LearnedItem[]> {
  const lower = new Set(existingNames.map(n => n.toLowerCase()));
  const all = await db.learnedItems.toArray();
  return all.filter(i => !lower.has(i.name.toLowerCase()));
}

// ── Unused Items (localStorage-backed) ──

const UNUSED_KEY = 'readiLi.unusedItems';

export function getUnusedNames(): Set<string> {
  const arr = JSON.parse(localStorage.getItem(UNUSED_KEY) || '[]') as string[];
  return new Set(arr);
}

export function markUnused(names: string[]) {
  const current = getUnusedNames();
  names.forEach(n => current.add(n.toLowerCase()));
  localStorage.setItem(UNUSED_KEY, JSON.stringify([...current]));
}

export function clearUnused(names: string[]) {
  const current = getUnusedNames();
  names.forEach(n => current.delete(n.toLowerCase()));
  localStorage.setItem(UNUSED_KEY, JSON.stringify([...current]));
}

// ── Utility ──

export function getTripDays(startDate: string, endDate: string): number {
  const start = new Date(startDate);
  const end = new Date(endDate);
  const diff = Math.round((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
  return Math.max(diff, 1);
}

export function getLongestStretch(
  startDate: string,
  endDate: string,
  hasLaundry: boolean,
  laundryDates: string[]
): number {
  const tripDays = getTripDays(startDate, endDate);
  if (!hasLaundry || laundryDates.length === 0) return tripDays;

  const start = new Date(startDate).getTime();
  const end = new Date(endDate).getTime();
  const sorted = laundryDates.map(d => new Date(d).getTime()).sort((a, b) => a - b);
  const boundaries = [start, ...sorted, end];

  let maxGap = 0;
  for (let i = 1; i < boundaries.length; i++) {
    const gap = Math.round((boundaries[i] - boundaries[i - 1]) / (1000 * 60 * 60 * 24));
    maxGap = Math.max(maxGap, gap);
  }
  return Math.max(maxGap, 1);
}

export function getFormattedDateRange(startDate: string, endDate: string): string {
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric', year: 'numeric' };
  const start = new Date(startDate).toLocaleDateString('en-US', opts);
  const end = new Date(endDate).toLocaleDateString('en-US', opts);
  return `${start} – ${end}`;
}
