export interface Trip {
  id: string;
  destination: string;
  startDate: string; // ISO date string
  endDate: string;
  hasLaundry: boolean;
  laundryDates: string[]; // ISO date strings
  rewearDays: number;
  activities: string[];
  isInternational: boolean;
  transportation: string[];
  feedbackRating: number;
  feedbackUnpacked: string[];
  feedbackWishlist: string;
  hasSubmittedFeedback: boolean;
}

export interface PackingItem {
  id: string;
  tripId: string;
  name: string;
  category: string;
  quantity: number;
  isPacked: boolean;
  isMustPack: boolean;
  isAutoGenerated: boolean;
}

export interface LearnedItem {
  name: string;
  category: string;
  quantity: number;
  isMustPack: boolean;
}
