import { useState } from 'react';
import { Tag, Folder, Hash } from 'lucide-react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { Stepper } from '../ui/Stepper';
import { addPackingItem, learnItem } from '../../db/hooks';

interface AddItemSheetProps {
  tripId: string;
  existingCategories: string[];
  preselectedCategory: string;
  isMustPack: boolean;
  onClose: () => void;
}

export function AddItemSheet({ tripId, existingCategories, preselectedCategory, isMustPack, onClose }: AddItemSheetProps) {
  const [name, setName] = useState('');
  const [category, setCategory] = useState(preselectedCategory);
  const [quantity, setQuantity] = useState(1);
  const [showCustom, setShowCustom] = useState(!preselectedCategory && !isMustPack);
  const [saving, setSaving] = useState(false);

  const canAdd = name.trim().length > 0 && (isMustPack || category.trim().length > 0);

  const handleAdd = async () => {
    if (saving) return;
    setSaving(true);
    try {
      const resolvedCategory = isMustPack ? 'Essentials' : category.trim();
      const item = await addPackingItem({
        tripId,
        name: name.trim(),
        category: resolvedCategory,
        quantity,
        isPacked: false,
        isMustPack,
        isAutoGenerated: false,
      });
      await learnItem({ name: item.name, category: item.category, quantity: item.quantity, isMustPack: item.isMustPack });
      onClose();
    } finally {
      setSaving(false);
    }
  };

  return (
    <div style={{ padding: '0 var(--card-px) 2rem' }}>
      <p className="text-[14px] text-[var(--text-secondary)] mb-6">
        {isMustPack ? 'This item will always appear at the top of your list.' : 'Add a custom item to your packing list.'}
      </p>

      <div className="flex flex-col gap-3">
        {/* Name */}
        <Card className="flex items-center gap-3">
          <Tag size={18} className="text-[var(--lavender)] shrink-0" />
          <input
            type="text"
            value={name}
            onChange={e => setName(e.target.value)}
            placeholder="Item name"
            className="flex-1 bg-transparent text-[16px] text-[var(--text-primary)] outline-none"
            autoFocus
          />
        </Card>

        {/* Category */}
        {!isMustPack && (
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[1.5px] text-[var(--blue-faint)] mb-2 px-1">Category</p>
            <div className="flex flex-wrap gap-2">
              {existingCategories.map(cat => (
                <button
                  key={cat}
                  onClick={() => { setCategory(cat); setShowCustom(false); }}
                  className={`px-3.5 py-2.5 rounded-lg text-[13px] font-medium transition-colors ${
                    category === cat && !showCustom
                      ? 'bg-[var(--lavender)] text-white'
                      : 'text-[var(--lavender)]'
                  }`}
                  style={category !== cat || showCustom ? { backgroundColor: 'color-mix(in srgb, var(--lavender) 12%, transparent)' } : {}}
                >
                  {cat}
                </button>
              ))}
              <button
                onClick={() => { setCategory(''); setShowCustom(true); }}
                className={`px-3.5 py-2.5 rounded-lg text-[13px] font-medium transition-colors flex items-center gap-1 ${
                  showCustom ? 'bg-[var(--lavender)] text-white' : 'text-[var(--text-secondary)] bg-[var(--border)] opacity-50'
                }`}
              >
                + Custom
              </button>
            </div>
            {showCustom && (
              <Card className="flex items-center gap-3 mt-2">
                <Folder size={18} className="text-[var(--lavender)] shrink-0" />
                <input
                  type="text"
                  value={category}
                  onChange={e => setCategory(e.target.value)}
                  placeholder="e.g. Misc, Snacks, Tech"
                  className="flex-1 bg-transparent text-[15px] text-[var(--text-primary)] outline-none"
                />
              </Card>
            )}
          </div>
        )}

        {/* Quantity */}
        <Card className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Hash size={18} className="text-[var(--lavender)]" />
            <span className="text-[16px] font-medium text-[var(--text-primary)]">Quantity</span>
          </div>
          <Stepper value={quantity} onChange={setQuantity} />
        </Card>
      </div>

      <div className="mt-6">
        <Button onClick={handleAdd} disabled={!canAdd || saving}>{saving ? 'Adding...' : 'Add to List'}</Button>
        {!canAdd && (
          <p className="text-[12px] text-[var(--text-secondary)] text-center mt-2.5">
            {name.trim().length === 0
              ? 'Enter an item name to continue'
              : 'Select or enter a category'}
          </p>
        )}
      </div>
    </div>
  );
}
