import { useState } from 'react';
import { MapPin, PlaneTakeoff, PlaneLanding, Clock, House, Globe, Car, TrainFront, Plane, Repeat } from 'lucide-react';
import { Button } from '../ui/Button';
import { Card } from '../ui/Card';
import { Toggle } from '../ui/Toggle';
import { Stepper } from '../ui/Stepper';
import { LucideIcon } from '../ui/LucideIcon';
import { ACTIVITY_LIST, EVENT_LIST, TRANSPORTS } from '../../lib/constants';
import { toISODate, addDays, getDatesInRange } from '../../lib/dateUtils';
import { updateTrip, deleteAutoGeneratedItems, addPackingItems, getLearnedNewItems } from '../../db/hooks';
import { generatePackingList } from '../../lib/packingCalculator';
import { fetchWeather } from '../../lib/weatherService';
import { db } from '../../db/database';
import type { Trip } from '../../db/models';

interface EditTripSheetProps {
  trip: Trip;
  onClose: () => void;
}

export function EditTripSheet({ trip, onClose }: EditTripSheetProps) {
  const [destination, setDestination] = useState(trip.destination);
  const [startDate, setStartDate] = useState(trip.startDate);
  const [endDate, setEndDate] = useState(trip.endDate);
  const [isInternational, setIsInternational] = useState(trip.isInternational);
  const [transportation, setTransportation] = useState(new Set(trip.transportation));
  const [hasLaundry, setHasLaundry] = useState(trip.hasLaundry);
  const [laundryDates, setLaundryDates] = useState(new Set(trip.laundryDates));
  const [rewearDays, setRewearDays] = useState(trip.rewearDays);
  const [activities, setActivities] = useState(new Set(trip.activities));
  const [saving, setSaving] = useState(false);

  const tripDays = Math.max(Math.round((new Date(endDate).getTime() - new Date(startDate).getTime()) / 86400000), 1);

  const handleSave = async () => {
    const trimmed = destination.trim();
    if (!trimmed) return;
    setSaving(true);

    try {
      let weather = null;
      try { weather = await fetchWeather(trimmed, startDate, endDate); } catch {}

      const tripData = {
        destination: trimmed, startDate, endDate, isInternational,
        transportation: [...transportation], hasLaundry,
        laundryDates: [...laundryDates], rewearDays, activities: [...activities],
      };

      // Get user-added items and their packed state
      const allItems = await db.packingItems.where('tripId').equals(trip.id).toArray();
      const userItems = allItems.filter(i => !i.isAutoGenerated);
      const packedNames = new Set(allItems.filter(i => i.isPacked).map(i => i.name.toLowerCase()));

      // Delete auto-generated, regenerate
      await deleteAutoGeneratedItems(trip.id);
      const drafts = generatePackingList(tripData, weather);
      const learnedNew = await getLearnedNewItems([...drafts.map(d => d.name), ...userItems.map(i => i.name)]);
      const allDrafts = [...drafts, ...learnedNew.map(li => ({
        name: li.name, category: li.category, quantity: li.quantity, isMustPack: li.isMustPack,
      }))];

      const userNames = new Set(userItems.map(i => i.name.toLowerCase()));
      const newItems = allDrafts
        .filter(d => !userNames.has(d.name.toLowerCase()))
        .map(d => ({
          tripId: trip.id, name: d.name, category: d.category, quantity: d.quantity,
          isPacked: packedNames.has(d.name.toLowerCase()), isMustPack: d.isMustPack, isAutoGenerated: true,
        }));

      await addPackingItems(newItems);
      await updateTrip(trip.id, tripData);
      onClose();
    } finally {
      setSaving(false);
    }
  };

  const toggleTransport = (id: string) => {
    setTransportation(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n; });
  };
  const toggleActivity = (id: string) => {
    setActivities(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n; });
  };
  const toggleLaundryDate = (d: string) => {
    setLaundryDates(prev => { const n = new Set(prev); n.has(d) ? n.delete(d) : n.add(d); return n; });
  };

  return (
    <div className="px-5 pb-8 max-h-[70dvh] overflow-y-auto">
      <div className="flex flex-col gap-5">
        {/* Destination */}
        <Card className="flex items-center gap-3 p-4">
          <MapPin size={18} className="text-[var(--lavender)] shrink-0" />
          <input type="text" value={destination} onChange={e => setDestination(e.target.value)}
            className="flex-1 bg-transparent text-[16px] text-[var(--text-primary)] outline-none" placeholder="Destination" />
        </Card>

        {/* Dates */}
        <div className="flex flex-col gap-2">
          <Card className="p-4 flex items-center gap-3">
            <PlaneTakeoff size={18} className="text-[var(--lavender)]" />
            <span className="text-[15px] font-medium text-[var(--text-primary)]">Departure</span>
            <span className="flex-1" />
            <input type="date" value={startDate} onChange={e => {
              setStartDate(e.target.value);
              if (new Date(e.target.value) >= new Date(endDate)) setEndDate(toISODate(addDays(new Date(e.target.value), 1)));
            }} className="bg-transparent text-[15px] text-[var(--lavender)] outline-none" />
          </Card>
          <Card className="p-4 flex items-center gap-3">
            <PlaneLanding size={18} className="text-[var(--lavender)]" />
            <span className="text-[15px] font-medium text-[var(--text-primary)]">Return</span>
            <span className="flex-1" />
            <input type="date" value={endDate} min={toISODate(addDays(new Date(startDate), 1))}
              onChange={e => setEndDate(e.target.value)} className="bg-transparent text-[15px] text-[var(--lavender)] outline-none" />
          </Card>
          <p className="text-center text-[14px] text-[var(--text-secondary)]">
            <Clock size={12} className="inline mr-1" />{tripDays} day{tripDays !== 1 ? 's' : ''}
          </p>
        </div>

        {/* Trip type */}
        <div className="grid grid-cols-2 gap-2">
          {[{ id: false, label: 'Domestic', icon: <House size={15} /> }, { id: true, label: 'International', icon: <Globe size={15} /> }].map(opt => (
            <button key={String(opt.id)} onClick={() => setIsInternational(opt.id as boolean)}
              className={`flex items-center justify-center gap-2 py-3 rounded-[12px] text-[15px] font-medium transition-colors ${
                isInternational === opt.id ? 'bg-[var(--lavender)] text-white' : 'bg-[var(--surface)] border border-[var(--border)] text-[var(--text-primary)]'
              }`}>
              {opt.icon} {opt.label}
            </button>
          ))}
        </div>

        {/* Transport */}
        <div className="grid grid-cols-3 gap-2">
          {TRANSPORTS.map(mode => {
            const sel = transportation.has(mode.id);
            const Icon = mode.id === 'Car' ? Car : mode.id === 'Train' ? TrainFront : Plane;
            return (
              <button key={mode.id} onClick={() => toggleTransport(mode.id)}
                className={`flex flex-col items-center gap-1.5 py-3 rounded-[12px] transition-colors ${
                  sel ? 'bg-[var(--lavender)] text-white' : 'bg-[var(--surface)] border border-[var(--border)]'
                }`}>
                <Icon size={20} className={sel ? 'text-white' : 'text-[var(--lavender)]'} />
                <span className="text-[13px] font-medium">{mode.label}</span>
              </button>
            );
          })}
        </div>

        {/* Laundry */}
        <Card className="p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <LucideIcon name="washing-machine" size={18} className="text-[var(--salmon)]" />
              <span className="text-[16px] font-medium text-[var(--text-primary)]">Laundry</span>
            </div>
            <Toggle checked={hasLaundry} onChange={val => { setHasLaundry(val); if (!val) setLaundryDates(new Set()); }} />
          </div>
          {hasLaundry && (
            <div className="grid grid-cols-7 gap-1 mt-3">
              {getDatesInRange(startDate, endDate).map(date => {
                const sel = laundryDates.has(date);
                const d = new Date(date);
                return (
                  <button key={date} onClick={() => toggleLaundryDate(date)}
                    className={`flex flex-col items-center py-1.5 rounded-md text-center transition-colors ${sel ? 'bg-[var(--lavender)] text-white' : 'hover:bg-[var(--border)]'}`}>
                    <span className="text-[9px]">{d.toLocaleDateString('en-US', { weekday: 'short' })}</span>
                    <span className="text-[12px] font-semibold">{d.getDate()}</span>
                  </button>
                );
              })}
            </div>
          )}
        </Card>

        {/* Rewear */}
        <Card className="p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Repeat size={18} className="text-[var(--lavender)]" />
            <span className="text-[16px] font-medium text-[var(--text-primary)]">Days per outfit</span>
          </div>
          <Stepper value={rewearDays} onChange={setRewearDays} min={1} max={5} />
        </Card>

        {/* Activities */}
        <div className="grid grid-cols-3 gap-2">
          {[...ACTIVITY_LIST, ...EVENT_LIST].map(act => {
            const sel = activities.has(act.id);
            return (
              <button key={act.id} onClick={() => toggleActivity(act.id)}
                className={`flex flex-col items-center gap-1 py-3 px-1 rounded-[12px] transition-colors ${
                  sel ? 'bg-[var(--lavender)] text-white' : 'bg-[var(--surface)] border border-[var(--border)]'
                }`}>
                <LucideIcon name={act.icon} size={20} className={sel ? 'text-white' : 'text-[var(--lavender)]'} />
                <span className={`text-[12px] font-medium text-center leading-tight ${sel ? 'text-white' : 'text-[var(--text-primary)]'}`}>{act.label}</span>
              </button>
            );
          })}
        </div>
      </div>

      <div className="mt-6">
        <Button onClick={handleSave} disabled={!destination.trim() || saving}>
          {saving ? 'Saving...' : 'Save Changes'}
        </Button>
      </div>
    </div>
  );
}
